remote_theme: pages-themes/midnight@v0.2.0
site_favicon: https://wanatry.github.io/assets/img/favicon.ico
name: .
title: null
description: Various projects & python coding
github:
is_project_page: false
